name: go-build
author: "Bekir Bekirov"
description: "Build Go project"
inputs:
  app-folder:
    description: "Application folder"
    required: false
    default: "."
  go-version:
    description: "Go version to use"
    required: false
    default: "1.15"
  build-only:
    description: "Run only build"
    required: false
    default: "false"
  test-only:
    description: "Run only test"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - name: Lint
      working-directory: ${{ inputs.app-folder }}
      run: |
        pwd
        if [[ ${{ inputs.build-only }} != true ]] && [[ ${{ inputs.test-only }} != true ]]
        then
          go get -u golang.org/x/lint/golint
          golint ./...
        fi
      shell: bash
    - name: vet
      working-directory: ${{ inputs.app-folder }}
      run: |
        pwd
        if [[ ${{ inputs.build-only }} != true ]] && [[ ${{ inputs.test-only }} != true ]]
        then
          go vet ./...
        fi
      shell: bash
    - name: Test
      working-directory: ${{ inputs.app-folder }}
      run: |
        pwd
        if [[ ${{ inputs.build-only }} != true ]]
        then
          go mod download
          go test ./... -v -coverprofile cover.out
        fi
      shell: bash
    - name: Build
      working-directory: ${{ inputs.app-folder }}
      run: |
        pwd
        if [[ ${{ inputs.test-only }} != true ]]
        then
          go mod download
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a
        fi
      shell: bash
