name: python-validate-code
author: "Famil Familzade"
description: "Test Python project"
runs:
  using: composite
  steps:
    - id: install-requirements
      name: "Install requirements"
      run: |
        python3 -m venv .venv &&  source .venv/bin/activate && pip install poetry && poetry install
      shell: bash
    - id: runing-tests
      name: "Running tests"
      run: |
        source .venv/bin/activate && pytest --cov=app --cov-report xml:coverage.xml
      shell: bash