name: npm
author: "PASHA Bank"
description: "Build, lint, test NPM project"
inputs:
  node-version:
    description: "NodeJS version to use"
    required: false
    default: "14"

  test:
    description: "Run test"
    required: false
    default: "false"

  build:
    description: "Run build"
    required: false
    default: "false"

  lint:
    description: "Run lint"
    required: false
    default: "false"

  style-lint:
    description: "Run stylelint"
    required: false
    default: "false"

  nls-check:
    description: "Run nls check"
    required: false
    default: "false"

  configure-csp-headers:
    description: "Configure CSP headers"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup NodeJS version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore npm cache
      uses: actions/cache@v2.1.4
      id: npm-cache
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: npm install
      if: steps.npm-cache.outputs.cache-hit != 'true'

    - name: Test
      shell: bash
      run: |
        if [[ ${{ inputs.test }} == true ]]
        then
          npm run test
        fi

    - name: Build
      shell: bash
      run: |
        if [[ ${{ inputs.build }} == true ]]
        then
          npm run build
        fi

    - name: Lint
      shell: bash
      run: |
        if [[ ${{ inputs.lint }} == true ]]
        then
          npm run lint
        fi

    - name: Stylelint
      shell: bash
      run: |
        if [[ ${{ inputs.style-lint }} == true ]]
        then
          npm run lint:style
        fi

    - name: NLS check
      shell: bash
      run: |
        if [[ ${{ inputs.nls-check }} == true ]]
        then
          npm run nls:check
        fi

    - name: Configure CSP headers
      shell: bash
      run: |
        if [[ ${{ inputs.configure-csp-headers }} == true ]]
        then
          npm run configure:csp-headers
        fi
